require('lang')
require('coq')
-- require('treesitterConfig')
require('autopairConfig')
-- require('nvimtreeConfig')
require('goConfig')
require('structrue')
require("icon-picker").setup({disable_legacy_commands = true})
require("noice").setup()
-- require("startup")
require("flutter-tools").setup {}
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
