require('lang')
require('coq')
-- require('treesitterConfig')
require('autopairConfig')
require('nvimtreeConfig')
require('goConfig')
require('structrue')
require("icon-picker").setup({disable_legacy_commands = true})
require("noice").setup()
require("startup")
require("flutter-tools").setup {}
